### ISSUE TITLE
hazy image and clean image have different size

### ISSUE THREAD

**Issue by lockxmonk** [nightldj/dehaze_release#4]
I found SOTS/indoor/hazy and SOTS/indoor/gt have different image size.So I encounter a error：

RuntimeError: input and target have different number of elements: input[8 x 3 x 460 x 620] has 6844800 elements, while target[8 x 3 x 480 x 640] has 7372800 elements at /opt/conda/conda-bld/pytorch_1518241554738/work/torch/lib/THCUNN/generic/MSECriterion.cu:15

How to solve this problem？

**Comment by nightldj** [comment]
Hi

I did not remember having this issue for my experiments. I checked my saved results, the size is 460 * 620. I did not save the dataset on my site. Maybe you can resize the image to 460 * 620.

Thanks.
